version: 2.1

jobs:
  build:
    working_directory: ~/aim-portfolio
    docker:
      - image: circleci/node:13.3.0

    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-npm-deps{{ checksum "package.json" }}
          - v1-npm-deps-
      - run: npm install
