version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers

    working_directory: ~/aim-portfolio

    steps:
      - checkout
      - run:
        name: "Install dependencies"
        command: npm install  
