version: 2.1

jobs:
  build:
    working_directory: ~/aim-portfolio
    docker:
      - image: circleci/node:13.3.0

    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
        paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
